title = "geekiam netlify deployment configuration file"

[build]
    publish = "dist"
    command = "yarn build"

[dev]
    framework="nuxt"
    command = "yarn dev" # Command to start your dev server
    port= 3850
    publish = "dist" # The path to your static content folder
    autoLaunch = true # a Boolean value that determines if Netlify Dev launches the local server address in your browser

[build.environment]
    NODE_VERSION = "18.14.0"



[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "DENY"
        X-XSS-Protection = "1; mode=block"
        Referrer-Policy = "no-referrer"
        X-Content-Type-Options = "nosniff"
        Strict-Transport-Security = "max-age=2592000; includeSubDomains; preload"
        Feature-Policy = "geolocation 'none'; midi 'none'; sync-xhr 'none';microphone 'none'; camera 'none'; magnetometer 'none'; gyroscope 'none'; speaker 'none'; fullscreen 'none'; payment 'none'"
        Content-Security-Policy = "default-src * 'unsafe-inline' 'unsafe-eval'; script-src * 'unsafe-inline' 'unsafe-eval'; connect-src * 'unsafe-inline'; img-src * data: blob: 'unsafe-inline'; frame-src *; style-src * 'unsafe-inline'"
# Branch deploy context:
# All deploys that are not from a pull/merge request
# or from the production branch will inherit these settings.
[context.branch-deploy]
command = "yarn build"
